### ISSUE TITLE
Unknown status code: 9001

### ISSUE THREAD

**Issue by speshiou** [googlesamples/android-play-places#1]
Always get this error (9001), I already replace my API key.

E PlaceAutocompleteAdapter: Error getting autocomplete prediction API call: Status{statusCode=unknown status code: 9001, resolution=null}

Btw, PlacePicker works fine, even I don't need an API key.
Thanks.

**Comment by speshiou** [comment]
I found it.
I have to enable "Places API for Android" in API console first.

**Comment by hereisderek** [comment]
notice, "Places API for Android" is not the same as "Places API"

**Comment by mallik482** [comment]
Hi I have enabled the Places API. But no luck still that error is showing please help me

**Comment by nabeelpkl** [comment]
i have enabled places api for android. and got it.
