### ISSUE TITLE
Unknown status code: 9001 

### ISSUE THREAD

**Issue by mallik482** [googlesamples/android-play-places#10]
I have run this application but getting this error even though  I enable google Places API

 Please help me on this

**Comment by jfschmakeit** [comment]
Please provide more information - where exactly are you seeing this issue?

**Comment by jfschmakeit** [comment]
This sounds like https://code.google.com/p/gmaps-api-issues/issues/detail?id=7933.
I'm closing this issue because it is not specific to the sample hosted here.
