### ISSUE TITLE
Cant Pick A Place

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-play-places#11]
i have update the api key in the manifest file, but when i run the app and click , Pick a place. it just loads and brings me back to the same page . i am unable to pick any place.

**Comment by jfschmakeit** [comment]
Please provide more information.
Are you running the PlaceComplete sample? Have you added your API key correctly and enabled the "Places API for Android" in the console?  https://developers.google.com/maps/documentation/android/start#get_an_android_certificate_and_the_google_maps_api_key

**Comment by ghost** [comment]
I fixed it. i put the wrong api key. now it works really good. 
Thank You
