### ISSUE TITLE
Placepicker UI

### ISSUE THREAD

**Issue by snosno2** [googlesamples/android-play-places#12]
How can i get places as place type(restaurant, ...) in placepicker UI dialog?
Placepicker.build have only method to set bound.

**Comment by chuks** [comment]
I am also looking for how to get places of particular types. It looks like currently there is no way to do this using PlacePicker. At least I don't see any documentation on how to do it. Looks like I'd have to revert to using the web service API ;(

**Comment by jfschmakeit** [comment]
This is currently not supported - see the documentation here: https://developers.google.com/places/android/placepicker

You could file a feature request in our API issue tracker if this is blocking you: https://code.google.com/p/gmaps-api-issues/
