### ISSUE TITLE
PlacePicker.IntentBuilder returns with resultCode 2

### ISSUE THREAD

**Issue by nghamilton** [googlesamples/android-play-places#13]
Starting the place picker ('Pick a Place') very briefly shows the place picker and then closes it before a place can be selected.

The returned resultCode is 2.

Running on Nexus 5, android 5.1.

Any ideas?

**Comment by nghamilton** [comment]
I was able to resolve this by removing all allowed android applications associated with the Places API key AND filling out the Consent screen in APIs & Auth of the console. Not sure which one fixed it, I'd guess the first.

(I used the SHA1 from ~/.android/debug.keystore and the example package name).

**Comment by jfschmakeit** [comment]
Sounds like you had a certificate/API key issue. Glad to hear you were able to resolve it.

**Comment by UsufJamil** [comment]
I did everything that was guided, still, the issue isn't solved. Anyone who can help me out.
