### ISSUE TITLE
How i can filter result by cities?

### ISSUE THREAD

**Issue by tplkn** [googlesamples/android-play-places#14]
When i try use filter `AutocompleteFilter.create(Arrays.asList(Place.TYPE_LOCALITY)` i always get network error, but sample work fine when i set filter as null

**Comment by jfschmakeit** [comment]
Only geocode and establishment are valid autocomplete filters at the moment. See this page for more details https://developers.google.com/places/android/autocomplete 
(address is not supported at the moment - we are working on updating the page.)

**Comment by chriscoderdr** [comment]
Will most of the places type be on the android library anywhere in the foresable future? most of the https://developers.google.com/places/supported_types are not in the library https://developers.google.com/android/reference/com/google/android/gms/location/places/AutocompleteFilter
