### ISSUE TITLE
How to use same api key for both maps and places in andorid

### ISSUE THREAD

**Issue by mallik482** [googlesamples/android-play-places#16]
I am using licensed google maps. So Google created separate project for maps. In that project I have created one api key(SHA1 fingerprint;package name). 

Now I want to use Places API for android. For that I think we need one more api key.

But manifest file allows only one key.

**Comment by jensneuse** [comment]
Just use the geo key.

**Comment by mallik482** [comment]
Geo key is created in separate project,because the project created by google is locked we can not enable other api's.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
