### ISSUE TITLE
Latitude and Longitude 

### ISSUE THREAD

**Issue by Shvet** [googlesamples/android-play-places#18]
Can i get Latitude and Longitude from response? I have point out place from Autocomplete to my map.

I am using one of my server api to show history of place where my user have visited in same autocomplete textview and for that i am getting latitude and longitude from server.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
