### ISSUE TITLE
sample of autocomplete give leak DataBuffer error message

### ISSUE THREAD

**Issue by jq** [googlesamples/android-play-places#2]
03-23 18:10:45.575  25173-25185/com.example.google.playservices.placecomplete E/DataBuffer﹕ Internal data leak within a DataBuffer object detected!  Be sure to explicitly call release() on all DataBuffer extending objects when you are done with them. (com.google.android.gms.location.places.PlaceBuffer@3ac0a41c)
3-23 18:10:57.262  25173-25173/com.example.google.playservices.placecomplete W/GmsClientEvents﹕ registerConnectionCallbacks(): listener zza{3b921345 id=0} is already registered
03-23 18:10:57.263  25173-25173/com.example.google.playservices.placecomplete W/GmsClientEvents﹕ registerConnectionFailedListener(): listener zza{3b921345 id=0} is already registered

**Comment by jfschmakeit** [comment]
Thank you for your report!

I haven't been able to replicate this issue. How did you trigger it? Do you have any steps to reproduce it?
(Which version and device are you running this on?)

**Comment by jfschmakeit** [comment]
Already fixed in fd51d8dad381048e21ec8e9d1233da43a806abe5 - Thanks!

**Comment by Evmilk** [comment]
hi, I have encountered the same problem.but not on this sample it is my application using play-games-plugin-for-unity plugin
when i called this method 
Social.localUser.Authenticate((bool success) =>
        {
        });
then it gave me this error
Internal data leak within a DataBuffer object detected!  Be sure to explicitly call release() on all DataBuffer extending objects when you are done with them. (internal object: com.google.android.gms.common.data.DataHolder@d7246b5)

thanks in advance!
