### ISSUE TITLE
Unable to instantiate activity ComponentInfo MainActivity

### ISSUE THREAD

**Issue by wax911** [googlesamples/android-play-places#20]
Attempting to run the program results in the following error: 
com.example.google.playservices.placepicker E/AndroidRuntime: Process: com.example.google.playservices.placepicker, PID: 9635

com.example.google.playservices.placepicker E/AndroidRuntime: java.lang.RuntimeException: Unable to instantiate activity 

ComponentInfo{com.example.google.playservices.placepicker/com.example.google.playservices.placepicker.MainActivity}: java.lang.ClassNotFoundException: 

Didn't find class "com.example.google.playservices.placepicker.MainActivity" on path: DexPathList[[zip file "/data/app/com.example.google.playservices.placepicker-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

Device Used is running 5.1.1 API 22 - Xperia SP

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
