### ISSUE TITLE
Placepicker does not launch when the internet is on 

### ISSUE THREAD

**Issue by AkashShetty** [googlesamples/android-play-places#21]
When I click on 'Pick a place' button the activity appears for a second and goes back (when the internet connection is on), whereas if the internet connection is switched off, it works fine.
Is it a problem with my API key?

Please help

**Comment by permenko** [comment]
Enable Google Places API for Android

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
