### ISSUE TITLE
PLACES_API_INVALID_APP

### ISSUE THREAD

**Issue by aldian** [googlesamples/android-play-places#22]
I am trying the PlaceComplete example on both simulator and real device.
I always got this error:

Error contacting API: Status{statusCode=PLACES_API_INVALID_APP,resolution=null}

What causes this error?
Thank you!

**Comment by yoshimaa** [comment]
check package name.
need to be same register package name at Google Developer Console as your project package name.

**Comment by aldian** [comment]
You are right. Thank you

**Comment by karansoni725** [comment]
Error contacting API: Status{statusCode=PLACES_API_INVALID_APP,resolution=null}

This Error is coming only Two phones , can anybody help me how to resolved this error, otherPhone is Going gud

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
