### ISSUE TITLE
java.lang.IllegalStateException: Already managing a GoogleApiClient with id 0

### ISSUE THREAD

**Issue by jagatappv** [googlesamples/android-play-places#23]
I am trying to add auto complete code into the fragments.
Its working fine when i push it first time and from subsequent tries it always getting this error.

Can you provide the code of auto complete with fragments?

Thanks

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
