### ISSUE TITLE
Application does not work with Marshmallow

### ISSUE THREAD

**Issue by seventhmoon** [googlesamples/android-play-places#28]
Application does not work with Marshmallow.
Does not work even manually grant the location permission.

**Comment by javawolfpack** [comment]
You need to update the meta-data value in the android manifest where it has "ADD_YOUR_API_KEY_HERE" with your own Google Maps Android API Key. It appears to work fine after doing so... had the same issue; however, I was looking for a stand alone resource file as is how the API key is stored in all the other Google Maps API examples I've been looking at. Hope this helps.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
