### ISSUE TITLE
Autocomplete error

### ISSUE THREAD

**Issue by IgorGanapolsky** [googlesamples/android-play-places#3]
I keep seeing the stacktrace:
"PlaceAutocompleteAdapter﹕ Error getting autocomplete prediction API call: Status{statusCode=NETWORK_ERROR, resolution=null}"

What's going on?

**Comment by wyemun** [comment]
Same here, followed exactly the implementation in the sample.

**Comment by jfschmakeit** [comment]
This could be caused by an incorrect API key.

Have you added your API key in the manifest and enabled the "Google Places API for Android" in the developer console for your project? 
See: https://developers.google.com/places/android/start#api-key and https://developers.google.com/places/android/signup

**Comment by jensneuse** [comment]
Make sure to not use google maps api key meta string but instead:

<meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="YOUR_API_KEY"/>
The maps api key needs to be deleted.

Also check if you initialized the GoogleApiClient as follows:

```
    mGoogleApiClient = new GoogleApiClient
            .Builder(_yourContext_)
            .addApi(Places.GEO_DATA_API)
            .addConnectionCallbacks(this)
            .addOnConnectionFailedListener(this)
            .build();
```
- don't forget to implement the interfaces needed but your IDE will inform you about that.

**Comment by IgorGanapolsky** [comment]
@jnscoding Shouldn't this be done in the project already?  It'd be strange to ask new developers to add all this new code to the project themselves.

**Comment by jensneuse** [comment]
True that @IgorGanapolsky.
Only thing i could imagine is you didn't change the API key in the manifest and/or there's something wrong with your API project/sha1key..

**Comment by renjith7189** [comment]
Is there any way by which we can bias the predictions to a particular location?

**Comment by jensneuse** [comment]
@renjith7189 Just define your custom bounds.

You can use this code to get bounds with a radius in meters:

``` java
import com.google.android.gms.maps.model.LatLng;
import com.google.android.gms.maps.model.LatLngBounds;
import com.google.maps.android.SphericalUtil;
public class LatLngBoundsFromRadius {
    public static LatLngBounds build(LatLng center,double radius){
        LatLngBounds latLngBounds = new LatLngBounds.Builder().
                include(SphericalUtil.computeOffset(center, radius, 0)).
                include(SphericalUtil.computeOffset(center, radius, 90)).
                include(SphericalUtil.computeOffset(center, radius, 180)).
                include(SphericalUtil.computeOffset(center, radius, 270)).build();
        return latLngBounds;
    }
}
```

You will need this lib:
http://googlemaps.github.io/android-maps-utils/

If your query returns any results within the bounds it'l return these items. Else it searches outside the bounds.

**Comment by lm2a** [comment]
Hello, I am trying to run the sample but I get:

Error getting autocomplete prediction API call: Status{statusCode=TIMEOUT, resolution=null}

Google Maps V2 Api Key was added to Manifest and the app was signed with the right certificate.

Any clues?

**Comment by jensneuse** [comment]
Could you post your API call code including Parameter definitions?

**Comment by jfschmakeit** [comment]
Please open separate issues to track problems with the samples.
For issues with the API please report them to our API issue tracker: https://code.google.com/p/gmaps-api-issues/

@lm2a This sounds like an API key issue - make sure that you have enabled the "Places API for Android" in the console. Also check that you have defined your API key as "com.google.android.geo.API_KEY" (and not the old ".maps." that you may already have in your manifest.)

**Comment by lm2a** [comment]
Hi, folks thanks for your help. , the main code is:

mGoogleApiClient = new GoogleApiClient.Builder(this)
            .enableAutoManage(this, 0 /\* clientId */, this)
            .addConnectionCallbacks(this)
            .addApi(Places.GEO_DATA_API)
            .build(); 

I just changed this:

<meta-data
            android:name="com.google.android.maps.v2.API_KEY"
            android:value="xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyx" />

by this:

<meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="xyxyxyxyxyxyxyxyxyxyxyxyxyxyxyx" />

And now the error message is: 

Error getting autocomplete prediction API call: Status{statusCode=unknown status code: 9001, resolution=null}

Thanks for you help ;)

**Comment by lm2a** [comment]
Hi, the problem was I registered my app for Places API, but the right registration is hide in Google Developer Console (damm redesign ;-(. I was setting Places API under Google Maps API, but the good one is "Places API for Android".
You can find this option by typing "Places API for Android" in search bar. The original response comes from other Stackoverflow guy, here his original post:

http://stackoverflow.com/questions/29270524/places-autocomplete-status-code-9001

**Comment by yosrah** [comment]
@jfschmakeit What if I'm using both google maps and places in my app. Do I add both meta tags to my manifest ?

**Comment by satishtamada** [comment]
<meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="ADD_YOUR_API_KEY_HERE"/>

**Comment by vickey20** [comment]
jnsone11 solution worked for me:

Make sure to not use google maps api key meta string but instead:

`android:name="com.google.android.geo.API_KEY"`
`android:value="YOUR_API_KEY"/>`
The maps api key needs to be deleted.

**Comment by shobhanaquickride** [comment]
I have used the right API key in my manifest with correct key name "com.google.android.geo.API_KEY", enabled the "Google Places API for Android" in the developer console and included Places.GEO_DATA_API while building GoogleApiClient

But still I see this status on some devices only - on most devices it works just fine, but on few devices, it fails with Status{statusCode=NETWORK_ERROR, resolution=null}"
Why does it fail only on some devices? How do I correct this?

**Comment by shuaibq3** [comment]
I have been facing the same issue. Api key meta in manifest is correct (both name and value).  api is activated from developer console. No api key restrictions so far, as the work is still under development. Adding restriction does not help. AutocompleteFilter is set to null.

Weird thing is it sometimes works. As in sometimes I get the desired response from Api. I have been working for about 3/4 days with it now, and it had worked fine until a few hours back. Now, on some rare cases I get a proper response from Api. Most of the time I am getting Status{statusCode=NETWORK_ERROR, resolution=null}. I have searched for a solution and came across a few suggestions but none of them worked for me. Any suggestions? Please help me out here, am on a tight timeline

**Comment by shashankvivek** [comment]
@shuaibq3 : any luck ? m stuck at the same position

**Comment by shuaibq3** [comment]
@shashankvivek:  no mate. It got fixed automatically. Try adding restriction to google api, enable/disable the api and changing the api key from developer console. Sometimes that works. Otherwise, no idea why that happens. After it was fixed the time, when i posted this question, i had faced it only once, and got fixed again pretty fast. I did the above things stated, though not sure if that was what fixed it.

**Comment by maheshj01** [comment]
> jnsone11 solution worked for me:
> 
> Make sure to not use google maps api key meta string but instead:
> 
> `android:name="com.google.android.geo.API_KEY"`
> `android:value="YOUR_API_KEY"/>`
> The maps api key needs to be deleted.

thanks mate this helped me
