### ISSUE TITLE
placePicker  NullPointerException

### ISSUE THREAD

**Issue by xiaoyan11** [googlesamples/android-play-places#31]
this is log:
FATAL EXCEPTION: main
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/com.google.android.location.places.ui.placepicker.v1.PlacePickerActivity}: java.lang.NullPointerException
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:525)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:  Caused by: java.lang.NullPointerException
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.maps.api.android.lib6.gmm6.m.ad.a(Unknown Source)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.maps.api.android.lib6.gmm6.c.h.a(Unknown Source)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.maps.api.android.lib6.gmm6.c.y.a(Unknown Source)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.maps.api.android.lib6.e.bd.a(Unknown Source)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.maps.api.android.lib6.e.ev.a(Unknown Source)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.maps.api.android.lib6.e.af.a(Unknown Source)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.android.gms.maps.internal.w.onTransact(SourceFile:66)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.os.Binder.transact(Binder.java)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.android.gms.maps.internal.aw.a(SourceFile:205)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.android.gms.maps.m.a(SourceFile:96)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.android.gms.c.c.b(SourceFile:210)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.android.gms.c.b.a(SourceFile:100)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.android.gms.maps.o.b(SourceFile:257)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.android.gms.maps.o.a(SourceFile:240)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.android.gms.c.a.a(SourceFile:162)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.android.gms.maps.MapView.a(SourceFile:382)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.android.location.places.ui.MarkerMapFragment.onActivityCreated(SourceFile:239)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.support.v4.app.Fragment.performActivityCreated(SourceFile:1970)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.support.v4.app.ag.a(SourceFile:1051)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.support.v4.app.ag.a(SourceFile:1207)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.support.v4.app.ag.c(SourceFile:1189)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.support.v4.app.ag.m(SourceFile:2001)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.support.v4.app.w.onStart(SourceFile:507)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.google.android.location.places.ui.placepicker.v1.PlacePickerActivity.onStart(SourceFile:235)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.app.Activity.performStart(Activity.java)
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)?
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)?
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java)?
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java)?
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java)?
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java)?
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java)?
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)?
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:525)?
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)?
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)?
01-15 09:09:29.345 17207-17207/? E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)?

**Comment by June-ENG** [comment]
https://code.google.com/p/gmaps-api-issues/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Introduced%20Fixed%20Summary%20Stars%20ApiType%20Internal&groupby=&sort=&id=9071

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
