### ISSUE TITLE
PLACE_API_INVALID App 

### ISSUE THREAD

**Issue by shanmugasundharamselvadurai** [googlesamples/android-play-places#32]
Hi  i am getting API invalid error message, i given my API Key which i configured in google place - API. Can you help me out !
Thanks.

**Comment by maelfosso** [comment]
Me too !!!

**Comment by praveen2gemini** [comment]
I'm also getting the same issue. Even though I have given API key after enabled related services in Goog console page.

**Comment by vipin10** [comment]
Have you activated the api key?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
