### ISSUE TITLE
Launching Place Picker intent destroys the launcher activity

### ISSUE THREAD

**Issue by ChandanPR** [googlesamples/android-play-places#35]
On Launching Place Picker intent, onStop() is called on launcher activity and the onDestroy is called() from the system. This is causing instabilities in the behaviour of the application.

OS: Android 5.0
Device: Samsung SM-N900
PlayServices Version: 8.7.03 (2645110-238)

We are not able to reproduce this on other devices with the same OS version or on the latest emulator.

**Comment by ChanSek** [comment]
Can you plz check the "Developer Options" in Settings and make sure the option "Don't Keep Activities" is not checked.

**Comment by ChandanPR** [comment]
Thanks a lot Chandrashekar. That was the problem.
