### ISSUE TITLE
AutoComplete Error

### ISSUE THREAD

**Issue by renjith7189** [googlesamples/android-play-places#4]
I followed the exact steps ,but AutoComplete is always throwing 'Timeout' error.Also  getting below error in logcat :
 java.lang.RuntimeException: Handler (android.os.Handler) {42ac3cd0} sending message to a Handler on a dead thread

**Comment by jfschmakeit** [comment]
Are you getting seeing this error when running the unmodified AutoComplete sample? Which device, version of Android and version of Google Play Services did you see this on?

Have you added your API key? 
The timeout issue could be related to https://github.com/googlesamples/android-play-places/issues/3.

**Comment by renjith7189** [comment]
Android version -> 4.1.2
Play Services version -> 7.0.99

I have added the api key(generated using debug keystore ) and enabled "Places API" in developer console as well. But I couldn't find "Google Places API for Android"  in console. Are both same or different?

**Comment by jfschmakeit** [comment]
There should be an entry for "Places API for Android - this section has more details: https://developers.google.com/places/android/signup#api-console

**Comment by jfschmakeit** [comment]
(It does look like there's an issue with the documentation - the API is called "Places API for Android". I'll file a request to get that updated - thanks!)

**Comment by renjith7189** [comment]
You mean to say "Places API for Android" are missing from developer console?

**Comment by Dhrupal** [comment]
@jfschmakeit : I have enabled api, put api key in menifest though getting following error E/PlaceAutocompleteAdapter﹕ Error getting autocomplete prediction API call: Status{statusCode=unknown status code: 9001, resolution=null}

**Comment by renjith7189** [comment]
I have enabled "Places API for Android", but still the timeout error is appearing everytime.

**Comment by Dhrupal** [comment]
have solved it.. I was enabling places api on latest api console, but it should keep on "Places API for Android" in old console like below image
![image](https://cloud.githubusercontent.com/assets/4310218/6913083/abfe2e3a-d798-11e4-893f-cb735e2e779d.png)

Also put your API key in menifest
 <meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="HERE"/>

**Comment by renjith7189** [comment]
My issue is also resolved. In my application, I am using maps api as well as Places api. In the manifest file, I had 'com.google.android.maps.v2.API_KEY' earlier.When com.google.android.geo.API_KEY is added to it, I was getting the error 'java.lang.RuntimeException: The API key can only be specified once. It is recommended that you use the meta-data tag with the name: com.google.android.maps.v2.API_KEY in the <application> element of AndroidManifest.xml'.

But if we use com.google.android.maps.v2.API_KEY alone, Places api wont work. Instead I used only "com.google.android.geo.API_KEY" , and both maps and places api are working now.

**Comment by brendan87** [comment]
+1 to @Dhrupal - I was having problems until I used the old developer console to enable "Places API for android" specifically.

**Comment by jfschmakeit** [comment]
Just to clarify, this is the issue tracker for the samples, not the API itself. Please file those issues on our API issue tracker: https://code.google.com/p/gmaps-api-issues/

The API you have to enable in the console is called "Places API for Android". This wasn't quite clear in the documentation, but it has already been updated.

@renjith7189 The error message isn't quite right and has already been fixed in an upcoming release. (It should tell you to us the new '.geo.' key.)
Just to be clear: You only need to specify the "com.google.android.geo.API_KEY" for both Places and  Maps APIs. There's no need to include the "com.google.android.maps.v2.API_KEY" anymore.

**Comment by Ramitraman** [comment]
Not able to get Place api resolved, always getting error
Error getting place predictions: Status{statusCode=unknown status code: 9002, resolution=null}
I am not sure what to do, please help me out to solve this problem.

**Comment by jazzbpn** [comment]
Status{statusCode=PLACES_API_ACCESS_NOT_CONFIGURED, resolution=null}
Please help to fix this issue..
