### ISSUE TITLE
Recent search + add work, home location

### ISSUE THREAD

**Issue by vishnu-prototyze** [googlesamples/android-play-places#40]
Hi, So i am using android Autocomplete widget. I was wondering how can i add recent places and add work, home location after i select a location. Any help will be appreciated.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
