### ISSUE TITLE
Getting Google play services out of date error. 

### ISSUE THREAD

**Issue by sandeep19** [googlesamples/android-play-places#42]
05-07 08:28:49.291  13922-13922/com.example.google.playservices.placepicker W/GooglePlayServicesUtil﹕ Google Play services out of date.  Requires 8487000 but found 6599434
05-07 08:28:49.295  13922-13922/com.example.google.playservices.placepicker E/GooglePlayServicesUtil﹕ GooglePlayServices not available due to error 2

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
