### ISSUE TITLE
android google place picker "android.os.BinderProxy"

### ISSUE THREAD

**Issue by kaderkayten** [googlesamples/android-play-places#43]
Hi,
I am using google place picker for in android but when it opens it immediately stop before you can pick a place.
This is the code:

try {

```
PlacePicker.IntentBuilder builder = new PlacePicker.IntentBuilder();
startActivityForResult(builder.build(this), PLACE_PICKER_REQUEST);

  } catch (GooglePlayServicesRepairableException e) {
e.printStackTrace();
} catch (GooglePlayServicesNotAvailableException e) {
e.printStackTrace();
 }
```

This is the error i am getting.

> token=android.os.BinderProxy@3431c3eb 
> Timeline: Activity_idle id: android.os.BinderProxy@3431c3eb time:37045782

**Comment by danleyb2** [comment]
@kaderkayten 
this helped me https://stackoverflow.com/questions/30067210/android-place-picker-closes-immediately-after-launch

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
