### ISSUE TITLE
Place Picker not showing search icon in Galaxy note5

### ISSUE THREAD

**Issue by rakesh-ideal** [googlesamples/android-play-places#45]
Place Picker not showing search icon on top right, this is happening only in Galaxy note5: https://www.dropbox.com/s/u1ujf11lh5mt12t/imgpsh_fullsize.jpeg?dl=0

My galaxy note5 have android 6.0.1 
http://stackoverflow.com/questions/37301384/place-picker-not-showing-search-icon-in-galaxy-note5/37307785#37307785

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
