### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1

### ISSUE THREAD

**Issue by juriigen** [googlesamples/android-play-places#48]
This happen to me everytime i write the address faster with keyboard prediction, can anyone help me how to fix this ?

**Comment by kishorer747-zz** [comment]
i am also facing the same issue. But it happens to me when I clear text faster and write faster also. Can anyone please add a solution?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
