### ISSUE TITLE
how to use in play-services-location:9.2.0

### ISSUE THREAD

**Issue by oops-gh** [googlesamples/android-play-places#52]
how to use in play-services-location:9.2.0,some function is error

**Comment by MDXDave** [comment]
Just use `compile 'com.google.android.gms:play-services-places:9.2.0'`

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
