### ISSUE TITLE
How to add search history to PlaceAutocompleteFragment in android studio 

### ISSUE THREAD

**Issue by rakhi191** [googlesamples/android-play-places#53]
Hi Team,

How to add search history list to PlacesAutocompleteFragment ?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
