### ISSUE TITLE
How to add particular place to the Autocomplete Filter

### ISSUE THREAD

**Issue by rajajawahar** [googlesamples/android-play-places#54]
I have to add a filter the address list from the particular place

**Comment by hiteshpatel0024** [comment]
The new place picker removes the step that allowed the user to browse around the location selected. I wish they bring that back instead of the new setup. We relied on that functionality in our app. In its current form it doesn't make any sense.

**Comment by 8Ozymandias** [comment]
@hiteshpatel0024 What kind of app did you have that required it?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
