### ISSUE TITLE
Nearby places not loading in 9.4.0 [5.0.2, 6.0.1]

### ISSUE THREAD

**Issue by rdadkins** [googlesamples/android-play-places#55]
After updating dependencies for places from 9.2.0 to 9.4.0, the nearby places does not function properly. My location is by landmarks and the 'Select this location' and 'Or choose a nearby place' is empty. The device I am testing on is HTC M7 with Android 5.0.2 as well as LG G5 with Android 6.0.1.
#5.0.2 Direct Issues
- I am unable to select places that appear around me unlike 6.0.1
- When moving the map to focus on other places, the nearby places list does not populate / refresh
- Nearby places will populate if I move the map away from my current location and press the GPS FAB (a noticeable length away from my current location)
#6.0.1 Direct Issues
- When moving the map to focus on other places, the nearby places list does not populate / refresh
- The nearby places list seems to refresh when I click the GPS FAB
- I am only able to select places that are a red circle with a white square on the inside instead of selecting places further away like in 9.2

**Comment by rdadkins** [comment]
This has been reported on [gmaps-api-issues](https://code.google.com/p/gmaps-api-issues/issues/detail?id=10337)

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
