### ISSUE TITLE
Dropping the pin doesn't select the place in place picker

### ISSUE THREAD

**Issue by das-abhilash** [googlesamples/android-play-places#56]
Inside the Place Picker map, I couldn't select the location when i try dropping the pin. When I select a place, the select button is disabled. I have tried with different versions of google play version. But the result is the same.
![screenshot_2016-09-07-20-44-49 1](https://cloud.githubusercontent.com/assets/15606145/18317565/398f43b4-753c-11e6-9ca3-c03a08d17198.png)

**Comment by Habibah28** [comment]
I have solved this so I don't quite know which one of these steps solves it

**In console.developer.google.com**
I enable Places API and Maps API, and download the json from [here](https://developers.google.com/mobile/add?platform=android&cntapi=signin&cnturl=https:%2F%2Fdevelopers.google.com%2Fidentity%2Fsign-in%2Fandroid%2Fsign-in%3Fconfigured%3Dtrue&cntlbl=Continue%20Adding%20Sign-In).

Also, get the API key from Credential page.

**In Android Studio**
In manifest, add
`<meta-data
            android:name="com.google.android.geo.API_KEY"
            android:value="YOUR_KEY_FROM_CREDENTIAL_PAGE"/>`

In `onCreate()`, add this (though I don't quite sure this is needed or not)
`private GoogleApiClient mGoogleApiClient;
mGoogleApiClient = new GoogleApiClient
                    .Builder(getActivity())
                    .addApi(Places.GEO_DATA_API)
                    .addApi(Places.PLACE_DETECTION_API)
                    .enableAutoManage(getActivity(), this)
                    .build();`

Everything else just follow the tutorial in [here](https://developers.google.com/places/android-api/start).

Hopefully this can help anyone in the future.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
