### ISSUE TITLE
sample outdated

### ISSUE THREAD

**Issue by SjoerdvGestel** [googlesamples/android-play-places#57]
com.google.android.gms.location.places.Places no longer exists in play-services-location:9.4.0

**Comment by SjoerdvGestel** [comment]
quick fix is to add com.google.android.gms:play-services-places:9.4.0

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
