### ISSUE TITLE
play services crash when i click on Pick a place - null pointer exception

### ISSUE THREAD

**Issue by v4-adi** [googlesamples/android-play-places#58]
Place services crashed pop up is shown when I click on Pick a place.

Device : COOLPAD Y91-100
OS : ANDROID 6.0.1
Play services version on phone : 10.0.84

Following is the crash logs:

Process: com.google.android.gms.ui, PID: 19319
11-21 20:02:00.255 19319 19319 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.google.android.gms/com.google.android.location.places.ui.placepicker.PlacePickerActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void maps.ad.y.o()' on a null object reference
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3103)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:150)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void maps.ad.y.o()' on a null object reference
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at maps.ad.R.b(Unknown Source)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at xx.onTransact(:com.google.android.gms.DynamiteModulesB:73)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:387)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at tsc.b(:com.google.android.gms:233)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at tps.a(:com.google.android.gms:124)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at oau.b(:com.google.android.gms:340)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at oaq.a(:com.google.android.gms:143)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at com.google.android.gms.maps.MapView.a(:com.google.android.gms:7332)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at almv.onResume(:com.google.android.gms:92)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at com.google.android.chimera.FragmentProxy.onResume(:com.google.android.gms:432)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at gm.a(:com.google.android.gms:12120)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at gm.a(:com.google.android.gms:1286)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at gm.a(:com.google.android.gms:1268)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at gm.p(:com.google.android.gms:2153)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at gm.a(:com.google.android.gms:12126)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at gm.a(:com.google.android.gms:1286)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at gm.a(:com.google.android.gms:1268)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at gm.p(:com.google.android.gms:2153)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at gc.onResumeFragments(:com.google.android.gms:11223)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at com.google.android.chimera.container.ActivityProxy.superOnResumeFragments(:com.google.android.gms:2418)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at com.google.android.chimera.Activity.onResumeFragments(:com.google.android.gms:372)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at com.google.android.chimera.Activity.publicOnResumeFragments(:com.google.android.gms:377)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at com.google.android.chimera.container.ActivityProxy.onResumeFragments(:com.google.android.gms:471)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at gc.onPostResume(:com.google.android.gms:511)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at com.google.android.chimera.container.ActivityProxy.superOnPostResume(:com.google.android.gms:2413)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at com.google.android.chimera.Activity.onPostResume(:com.google.android.gms:363)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at com.google.android.chimera.appcompat.AppCompatActivity.onPostResume(:com.google.android.gms:183)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at com.google.android.chimera.Activity.publicOnPostResume(:com.google.android.gms:368)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at com.google.android.chimera.container.ActivityProxy.onPostResume(:com.google.android.gms:462)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6385)
11-21 20:02:00.255 19319 19319 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)

**Comment by vytautokas** [comment]
Same problem here. LG G3. There was no problem one month ago. I think google play services has been updated to newer. 

Google Play Services on device: 11.0.55(430-156917137)

**Comment by CTNCardoso** [comment]
App:
https://play.google.com/store/apps/details?id=br.com.ctncardoso.ctncar
Play-services version: 11.0.1

The same problem is occurring on the following devices.

API: 23
Version: 6.0.1
Version Number: MMB29M
Language: pt
Locale: português (Brasil)
Fabricante: LENOVO
Model: Lenovo A6020l36
---
API: 23
Version: 6.0
Version Number: MRA58K
Language: en
Locale: English (United Kingdom)
Fabricante: LGE
Model: LG-H815
--
API: 23
Version: 6.0
Version Number: MRA58K
Language: pt
Locale: português (Brasil)
Fabricante: LGE
Model: LG-K430
---
API: 23
Version: 6.0.1
Version Number: MMB29M
Language: en
Locale: English (United Kingdom)
Fabricante: bq
Model: Aquaris X5
---
API: 22
Version: 5.1.1
Version Number: LMY47V
Language: pt
Locale: português (Brasil)
Fabricante: LGE
Model: LG-K130
---
API: 23
Version: 6.0.1
Version Number: 26.3.B.1.33
Language: pt
Locale: português (Brasil)
Fabricante: Sony
Model: E2363
---
API: 23
Version: 6.0
Version Number: MRA58K
Language: es
Locale: español (Estados Unidos)
Fabricante: LGE
Model: LG-D851
---

**Comment by CTNCardoso** [comment]
App:
https://play.google.com/store/apps/details?id=br.com.ctncardoso.ctncar
Play-services version: 11.0.1

The same problem is occurring on the following devices.

API: 23
Version: 6.0.1
Version Number: MMB29M
Language: pt
Locale: português (Brasil)
Fabricante: LENOVO
Model: Lenovo A6020l36
---
API: 23
Version: 6.0
Version Number: MRA58K
Language: en
Locale: English (United Kingdom)
Fabricante: LGE
Model: LG-H815
--
API: 23
Version: 6.0
Version Number: MRA58K
Language: pt
Locale: português (Brasil)
Fabricante: LGE
Model: LG-K430
---
API: 23
Version: 6.0.1
Version Number: MMB29M
Language: en
Locale: English (United Kingdom)
Fabricante: bq
Model: Aquaris X5
---
API: 22
Version: 5.1.1
Version Number: LMY47V
Language: pt
Locale: português (Brasil)
Fabricante: LGE
Model: LG-K130
---
API: 23
Version: 6.0.1
Version Number: 26.3.B.1.33
Language: pt
Locale: português (Brasil)
Fabricante: Sony
Model: E2363
---
API: 23
Version: 6.0
Version Number: MRA58K
Language: es
Locale: español (Estados Unidos)
Fabricante: LGE
Model: LG-D851
---

**Comment by CTNCardoso** [comment]
App:
https://play.google.com/store/apps/details?id=br.com.ctncardoso.ctncar
Play-services version: 11.0.1

The same problem is occurring on the following devices.

API: 23
Version: 6.0.1
Version Number: MMB29M
Language: pt
Locale: português (Brasil)
Fabricante: LENOVO
Model: Lenovo A6020l36

API: 23
Version: 6.0
Version Number: MRA58K
Language: en
Locale: English (United Kingdom)
Fabricante: LGE
Model: LG-H815

API: 23
Version: 6.0
Version Number: MRA58K
Language: pt
Locale: português (Brasil)
Fabricante: LGE
Model: LG-K430

API: 23
Version: 6.0.1
Version Number: MMB29M
Language: en
Locale: English (United Kingdom)
Fabricante: bq
Model: Aquaris X5

API: 22
Version: 5.1.1
Version Number: LMY47V
Language: pt
Locale: português (Brasil)
Fabricante: LGE
Model: LG-K130

API: 23
Version: 6.0.1
Version Number: 26.3.B.1.33
Language: pt
Locale: português (Brasil)
Fabricante: Sony
Model: E2363

API: 23
Version: 6.0
Version Number: MRA58K
Language: es
Locale: español (Estados Unidos)
Fabricante: LGE
Model: LG-D851

**Comment by CTNCardoso** [comment]
App:
https://play.google.com/store/apps/details?id=br.com.ctncardoso.ctncar
Play-services version: 11.0.1

The same problem is occurring on the following devices.


APARELHO
Aparelho Redmi 4 Pro (markw) 
Fabricante Xiaomi 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Português 
Marca da CPU Qualcomm 
Modelo de CPU MSM8953 
Plataforma nativa armeabi-v7a, armeabi, arm64-v8a 
RAM (MB) 3072 
Tamanho da tela 1080 × 1920 
Densidade da tela (dpi) 480 
Versão OpenGL ES 3.1 
SO Android 6.0

Aparelho Redmi 4 Pro (markw) 
Fabricante Xiaomi 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Russo 
Marca da CPU Qualcomm 
Modelo de CPU MSM8953 
Plataforma nativa armeabi-v7a, armeabi, arm64-v8a 
RAM (MB) 3072 
Tamanho da tela 1080 × 1920 
Densidade da tela (dpi) 480 
Versão OpenGL ES 3.1 
SO Android 6.0

Aparelho LG K10 LTE (m253) 
Fabricante LGE 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Português 
Marca da CPU Mediatek 
Modelo de CPU MT6753 
Plataforma nativa armeabi-v7a, armeabi 
RAM (MB) 1536 
Tamanho da tela 720 × 1280 
Densidade da tela (dpi) 320 
Versão OpenGL ES 3.0 	
SO Android 6.0

Aparelho HTC Desire 10 pro (htc_a56dj_pro_dugl) 
Fabricante HTC 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Inglês 
Marca da CPU Mediatek 
Modelo de CPU MT6577 
Plataforma nativa armeabi-v7a, armeabi, arm64-v8a 
RAM (MB) 2048 
Tamanho da tela 1080 × 1920 
Densidade da tela (dpi) 480 
Versão OpenGL ES 3.0 
SO Android 6.0

Aparelho LG X power (mk6p) 
Fabricante LGE 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Português 
Marca da CPU Mediatek 
Modelo de CPU MT6735 
Plataforma nativa armeabi-v7a, armeabi 
RAM (MB) 2048 
Tamanho da tela 720 × 1280 
Densidade da tela (dpi) 320 
Versão OpenGL ES 3.0 
SO Android 6.0

Aparelho Mi 5 (gemini) 
Fabricante Xiaomi 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Russo 
Marca da CPU Qualcomm 
Modelo de CPU MSM8996 
Plataforma nativa armeabi-v7a, armeabi, arm64-v8a 
RAM (MB) 4096 
Tamanho da tela 1080 × 1920 
Densidade da tela (dpi) 480 
Versão OpenGL ES 3.1 
SO Android 6.0

Aparelho Redmi Note 4 (mido) 
Fabricante Xiaomi 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Inglês 
Marca da CPU Qualcomm 
Modelo de CPU MSM8953 
Plataforma nativa armeabi-v7a, armeabi, arm64-v8a 
RAM (MB) 3072 
Tamanho da tela 1080 × 1920 
Densidade da tela (dpi) 480 
Versão OpenGL ES 3.1 
SO Android 6.0

Aparelho Lenovo K5 (A6020l36) 
Fabricante Lenovo Mobile 
Tipo de dispositivo Smartphone 
Idioma do dispositivo Português 
Marca da CPU Qualcomm 
Modelo de CPU MSM8929 
Plataforma nativa armeabi-v7a, armeabi, arm64-v8a 
RAM (MB) 2048 
Tamanho da tela 1080 × 1920 
Densidade da tela (dpi) 480 
Versão OpenGL ES 3.0 
SO Android 6.0

**Comment by TangGee** [comment]
The same problem is occurring on the following device

xiaomi

**Comment by vytautokas** [comment]
Solved the problem. 
I have enabled Google Places API Web Service in Google Cloud Console. 
This is strange that it helped.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
