### ISSUE TITLE
PlaceAutocomplete.IntentBuilder intent with only english language.

### ISSUE THREAD

**Issue by MikhilPastagia** [googlesamples/android-play-places#60]
Hello, 
I uses PlaceAutocomplete.IntentBuilder for place search and selection. But when locale is change its was searching with locale language. I want to open PlaceAutocomplete.IntentBuilder with only English language.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
