### ISSUE TITLE
Missing documentation in Android Studio

### ISSUE THREAD

**Issue by mtrakal** [googlesamples/android-play-places#61]
https://developers.google.com/places/android-api/start

Any version of Google Play Services  miss any documentation for Places. Documentation is possible to search on website, but not in Android Studio 3.0, when develop and need to show documentation :/.

WTF, it's deprecated, but what should I use instead? Ok I'll look on documentation, fuck, no documentation :/. I must go to website, search for it... Sooooo productive. 

![clipboard01](https://user-images.githubusercontent.com/1458891/27134654-7dfda34a-5116-11e7-8e05-6d748e52397c.png)

Android Studio 3.0 Canary 3
Build #AI-171.4056697, built on June 1, 2017
JRE: 1.8.0_112-release-736 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
classpath 'com.android.tools.build:gradle:2.3.1'
classpath 'com.google.gms:google-services:3.0.0'
playServicesVersion = '10.2.6' (on 11.0.0 it's same)

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
