### ISSUE TITLE
PlacePicker Crash on Xiaomi Redmi 4

### ISSUE THREAD

**Issue by alexmirash** [googlesamples/android-play-places#62]
Attemp to launch PlacePicker causes a crash on specific device.
Xiaomi Redmi 4, Android 6.0.1, MIUI Global 8.2

java.lang.RuntimeException: Unable to resume activity {com.google.android.gms/com.google.android.location.places.ui.placepicker.PlacePickerActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.bn.o()' on a null object reference

**Comment by JackyJacksonjj** [comment]
Same problem on: 
Xiaomi Redmi Note 3 Pro, Android 5.1.1 LMY47V, MIUI Global 8.0 (8.0.6.0 (LHOMIDG))

**Comment by Queskr** [comment]
Same here!

**Comment by snorkel123** [comment]
Same problem here:
Xiaomi Redmi 3S, Android 6.0.1, MIUI Global 7.5

**Comment by sidiqpermana** [comment]
Same here!

**Comment by Latief-Anwar** [comment]
same here

**Comment by vikskod** [comment]
still not fixed disappointing :(

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
