### ISSUE TITLE
Fragment in fullscreen mode not possible

### ISSUE THREAD

**Issue by adnxy** [googlesamples/android-play-places#63]
Inside my fragment I'm using Google Places search and creating new markers from results. Everything is working fine, but I need to customize this fragment.Is it possible to customize appearance of fragment without using intent and Activity.I need to open places search in full screen and with black background

Here is my XML :

```
<fragment
  android:id="@+id/place_autocomplete_fragment"
  android:layout_width="0dp"
  android:layout_height="0dp"
  app:layout_constraintTop_toTopOf="@+id/gl_h_0p"
  app:layout_constraintBottom_toTopOf="@+id/gl_h_100p"
  app:layout_constraintRight_toRightOf="@+id/gl_v_980p"
  app:layout_constraintLeft_toLeftOf="@+id/gl_v_900p"
android:name="com.google.android.gms.location.places.ui.PlaceAutocompleteFragment"
  />
```
Here is fragment:

 @Override public void onViewCreated(View view, Bundle savedInstanceState) {
    super.onViewCreated(view, savedInstanceState);
    autocompleteFragment  = (PlaceAutocompleteFragment)getActivity().
   getFragmentManager().findFragmentById(R.id.place_autocomplete_fragment);
    autocompleteFragment.setOnPlaceSelectedListener(this);

  }

 ```
@Override
  public void onPlaceSelected(Place place) {
    Log.d("Place","selected");
  }

  @Override public void onError(Status status) {
    Log.d("Place","error");

  }


```

**Comment by samramez** [comment]
Where you able to figure this out @adnxy ?
I have the same exact problem where I can't use Intents.

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
