### ISSUE TITLE
How to set more than one country to the Autocomplete Filter

### ISSUE THREAD

**Issue by satyam-27** [googlesamples/android-play-places#69]
`val autoCompleteFilter = AutocompleteFilter.Builder().setTypeFilter(Place.TYPE_COUNTRY)
                .setCountry("IN")
                .build()`

> I want to restrict results for more than one country, How can I achieve that?

**Comment by hamidsn** [comment]
Maybe ['us', 'pr', 'vi', 'gu', 'mp'] ?!?
Documentation says only one country https://developers.google.com/android/reference/com/google/android/gms/location/places/AutocompleteFilter.Builder

**Comment by satyam-27** [comment]
`setCountry("IN")`

above method takes only string but you are suggesting string array.
Cant pass string array as string.
Is there are way to set more than one country?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
