### ISSUE TITLE
problems to get this project working in eclipse

### ISSUE THREAD

**Issue by benddror** [googlesamples/android-play-places#7]
hey

i got an error after importing the autocomlete prohect in the in the folder of values v21 ->base-template-styles.xml 
rhe following lines of stley returns me compile error
    <style name="Theme.Base" parent="android:Theme.Material.Light">
    </style>
the error is "error: Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Material.Light'."
can somebody please help me how to solve it?

**Comment by jfschmakeit** [comment]
It sounds like you are missing API v21 in your Android SDK. Please make sure you have the latest SDK platform and build tools installed from the Android SDK Manager.
You will also need the v4 and v13 support libraries. See: https://developer.android.com/tools/support-library/setup.html

(If you are just getting started, I'd recommend using Android Studio instead: http://developer.android.com/tools/studio/ )
