### ISSUE TITLE
How to restrict to particular state like Texsas,Florida etc??

### ISSUE THREAD

**Issue by sairajkishore** [googlesamples/android-play-places#70]
How to restrict AutocompleteFilter to particular state like Texsas,Florida etc??

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
