### ISSUE TITLE
How to add "powered by google logo" to PlaceAutocompleteAdapter ??

### ISSUE THREAD

**Issue by sairajkishore** [googlesamples/android-play-places#71]
How to add "powered by google logo" to PlaceAutocompleteAdapter ??

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
