### ISSUE TITLE
PlacePicker with defined location zoomed too much compared to none-defined `LatLng`

### ISSUE THREAD

**Issue by Ric17101** [googlesamples/android-play-places#72]
```
const PLACE_PICKER_REQUEST = 123;
public void editPlace(View view) {
        try {
            PlacePicker.IntentBuilder builder = new PlacePicker.IntentBuilder();
            LatLngBounds bounds = LatLngBounds.builder().include(new LatLng(xx.xxxxx, xx.xxxxx)).build();
            // OR
            // LatLngBounds latLngBounds = new LatLngBounds(new LatLng(xx.xxxxx, xx.xxxxx),
            // new LatLng(xx.xxxxx, xx.xxxxx));

            builder.setLatLngBounds(bounds);

            startActivityForResult(builder.build(getActivity()), PLACE_PICKER_REQUEST);
        } catch (GooglePlayServicesRepairableException | GooglePlayServicesNotAvailableException e) {
            e.printStackTrace();
        }
    }
```

**Comment by Ric17101** [comment]
will it be possible to set the zomming scale or ratio of the Map when using PlacePicker?

**Comment by trotterellone** [comment]
quote. Did you find out a solution?

**Comment by trotterellone** [comment]
I recommend this:

 public void goPlacePicker(View view) {
        PlacePicker.IntentBuilder builder = new PlacePicker.IntentBuilder();

        LatLngBounds latLngBounds = getLatLngBounds(new LatLng(41.890880, 12.493030));
        builder.setLatLngBounds(latLngBounds);

        try {
            startActivityForResult(builder.build(PlacePickerActivity.this), PLACE_PICKER_REQUEST);

        } catch (GooglePlayServicesRepairableException e) {
            e.printStackTrace();
        } catch (GooglePlayServicesNotAvailableException e) {
            e.printStackTrace();
        }
    }

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
