### ISSUE TITLE
Places autocomplete sort by distance

### ISSUE THREAD

**Issue by chaitanya-exp** [googlesamples/android-play-places#73]
How do we get predictions sorted by distance from approximate current location?

**Comment by dmahely** [comment]
Were you able to do this? I've just started working with the Places SDK and I'd like to implement that feature in my app.

**Comment by chaitanya-exp** [comment]
No

**Comment by isairuiz** [comment]
Has been resolved yet? if yes please post the solution, thanks!

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
