### ISSUE TITLE
Can't open Android Studio

### ISSUE THREAD

**Issue by abalta** [googlesamples/android-play-places#8]
When try to open android studio, It says "Gradle location unknown".

**Comment by peternagy95** [comment]
Did you choose "Import Project" when you opened it? It also occured for me when I clicked on the "Open an existing android studio project" .

**Comment by abalta** [comment]
No, I directly choose open project.

**Comment by peternagy95** [comment]
try to "import project"

**Comment by jfschmakeit** [comment]
Yes, please use "Import Project" and select the project directory to load the project in Android Studio.
