### ISSUE TITLE
Place Detection API is returning INTERNAL_ERROR

### ISSUE THREAD

**Issue by tyler-gh** [googlesamples/android-play-places#9]
PlaceLikelihoodBuffer{status=Status{statusCode=INTERNAL_ERROR, resolution=null}, attributions=null}

``` java
PendingResult<PlaceLikelihoodBuffer> result = Places.PlaceDetectionApi.getCurrentPlace(googleApiClient, null);
        result.setResultCallback(new ResultCallback<PlaceLikelihoodBuffer>() {
            @Override
            public void onResult(PlaceLikelihoodBuffer likelyPlaces) {
                Log.e(likelyPlaces.toString());
                try {
                    // my code
                }finally {
                    likelyPlaces.release();
                }
            }
        });
```

**Comment by tyler-gh** [comment]
Another thing to note. I also have several autocomplete views that work perfectly fine in the same app.

**Comment by jfschmakeit** [comment]
Are you getting this error when running the PlaceComplete sample from this repository? Have you declared all required permissions?

**Comment by tyler-gh** [comment]
It turns out that I was only getting this error when using a Samsung tablet. It worked perfectly fine on any phone that I tried. It obviously wasn't something I was doing wrong on my side though as it worked everywhere except for in that situation.

**Comment by jfschmakeit** [comment]
This is very curious.
What model was is this? Which version of Android is it running?

**Comment by jfschmakeit** [comment]
Could you also double check which version of Google Play Services is installed on that particular device?

**Comment by jfschmakeit** [comment]
If you are still seeing this, could you file an issue on our API issue tracker and provide all required details? This one here is for the samples code.
https://code.google.com/p/gmaps-api-issues/

Thanks!

**Comment by SaitejaP** [comment]
I am facing exact issue on moto g and moto x. I don't think its device specific issue. Auto complete works fine but `getCurrentPlace` gives error.

**Comment by AseemWangoo** [comment]
PlaceLikelihoodBuffer{status=Status{statusCode=INTERNAL_ERROR, resolution=null}, attributions=null}..

getting this error..please suggest

**Comment by LaercioMetzner** [comment]
I got the same problem, with no reasonably cause. Any help would be appreciated.

**Comment by AseemWangoo** [comment]
if you are running the code in emulator then please check its sdkversion.
If its 23 then you need to check whether your emulator device has been given permission.

**Comment by LaercioMetzner** [comment]
I'm not using an emulator device. I just cleaned all the Google Play Services data and forced it to stop, then things worked. Now I think that it can be an issue inside Google Play Services app. That can get me in a big trouble if it happens to the future users of my app.

**Comment by AseemWangoo** [comment]
I don't think that is actually going to help you in ahead time.

On Friday, 19 February 2016, Laercio Metzner notifications@github.com
wrote:

> I'm not using an emulator device. I just cleaned all the Google Play
> Services data and forced it to stop, then things worked. Now I think that
> it can be a problem inside Google Play Services app. I think it can get me
> in a big trouble if it happens to the future users of my app.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/googlesamples/android-play-places/issues/9#issuecomment-185972582
> .

## 

Regards
